// Generated by `python -m boarddd.model --write` from python/src/boarddd/copper.py. Do not edit.
// The boarddd/copper@1 model; see docs/copper.md.

import type { Source, SourceFile, Vec2 } from '../model/board.js';
export type { Source, SourceFile, Vec2 };

export type CopperSchemaId = "boarddd/copper@1";

/** The copper of one board revision. */
export interface Copper {
  /** Format id. */
  schema: "boarddd/copper@1";
  /** The board@1 document's name this copper belongs to. */
  board: string;
  /** Provenance. */
  source: Source;
  /** Length unit. */
  units: "mm";
  /** Coordinate frame: x right, y up, seen from the top. */
  frame: "board";
  /** Copper layer ids, top to bottom. */
  layers: string[];
  /** Net names the copper uses ('' first when some copper has no net). */
  nets?: string[];
  /** Tracks. */
  tracks?: Track[];
  /** Vias. */
  vias?: Via[];
  /** Zone fills per layer (pours, teardrops, Gerber regions). */
  zones?: Zone[];
  /** Keepouts (rule areas). */
  keepouts?: Keepout[];
  /** Pads as copper. */
  pads?: CopperPad[];
  /** Net ties. */
  net_ties?: NetTie[];
  /** Pour area per layer and net, for reference-plane detection. */
  planes?: Plane[];
  /** What the reader could not represent, or found suspicious (stale fills). */
  warnings?: string[];
  /** Free-form application data (not interpreted by boarddd). */
  meta?: Record<string, unknown>;
}

/** A routed track: a straight segment, or an arc through ``mid``; round ends of diameter ``width``. */
export interface Track {
  /** Copper layer id ('F.Cu', 'In1.Cu'). */
  layer: string;
  /** Net name ('' = no net). */
  net: string;
  /** Track width, mm. */
  width: number;
  /** First end, board frame. */
  start: Vec2;
  /** Second end, board frame. */
  end: Vec2;
  /** Arcs: the point on the arc halfway between start and end (KiCad's (mid)); null for a straight segment. */
  mid?: Vec2 | null;
  /** Source id (KiCad uuid), when the source has one. */
  id?: string | null;
}

/** A plated via joining copper layers ``span[0]`` to ``span[1]`` (top to bottom). */
export interface Via {
  /** Centre, board frame. */
  at: Vec2;
  /** Net name ('' = no net). */
  net: string;
  /** Pad (annular ring) diameter, mm: the largest when it differs per layer. */
  diameter: number;
  /** Finished hole diameter, mm; 0 when the source has none (Gerber without drill files) or writes a placeholder. */
  drill: number;
  /** First and last copper layer the hole connects, top to bottom. */
  span: [string, string];
  /** From the span ('through': outer to outer) or the source's own type (KiCad blind/micro). */
  type: "through" | "blind" | "buried" | "micro";
  /** Layers in the span with an annular ring, when not all (KiCad 'remove unused layers', Gerber); null = all. */
  pad_layers?: string[] | null;
  /** Per-layer pad diameters, when they differ from ``diameter``. */
  padstack?: ViaPad[] | null;
  /** Source id (KiCad uuid). */
  id?: string | null;
}

/** A via's annular ring on one layer, when it differs from the via's default (KiCad 10 padstacks, Gerber). */
export interface ViaPad {
  /** Copper layer id. */
  layer: string;
  /** Pad diameter on this layer, mm. */
  diameter: number;
}

/** Copper of one zone (pour) on one layer: a multi-layer zone has one entry per layer, sharing ``id``. */
export interface Zone {
  /** Copper layer id. */
  layer: string;
  /** Net name ('' = no net). */
  net: string;
  /** 'pour': a KiCad zone; 'teardrop': a KiCad teardrop zone; 'shape': a filled copper drawing (KiCad gr_/fp_ polygons, rectangles, circles on copper; Gerber EtchedComponent regions); 'region': other filled copper from a Gerber/ODB++ region, which does not say what drew it. */
  kind: "pour" | "teardrop" | "shape" | "region";
  /** The filled copper as the source stores it (may be stale: see ``stale``). */
  fill: FillPolygon[];
  /** Filled area, mm^2 (outlines minus holes). */
  area: number;
  /** The zone's own boundary as drawn (KiCad (polygon)); null for regions. */
  outline?: Vec2[] | null;
  /** KiCad zone priority (higher fills first). */
  priority?: number | null;
  /** Zone name, when set. */
  name?: string | null;
  /** False when the zone has no fill at all on this layer (never filled, or filled before it was moved). */
  filled?: boolean;
  /** True when a fill check found the fill out of date (copper of another net inside it); null = not checked. */
  stale?: boolean | null;
  /** Source id (KiCad zone uuid), shared by a multi-layer zone's entries. */
  id?: string | null;
}

/** One filled area: an outer loop (counter-clockwise) minus holes (clockwise); loops implicitly closed. */
export interface FillPolygon {
  /** Outer boundary. */
  outline: Vec2[];
  /** Holes inside it. */
  holes?: Vec2[][];
}

/** A keepout (KiCad rule area) on one or more copper layers. */
export interface Keepout {
  /** Copper layer ids it applies to. */
  layers: string[];
  /** Boundary, board frame. */
  outline: Vec2[];
  /** What it forbids. */
  rules?: KeepoutRules;
  /** Rule area name, when set. */
  name?: string | null;
  /** The footprint (reference) it belongs to, for footprint keepouts. */
  ref?: string | null;
  /** Source id (KiCad uuid). */
  id?: string | null;
}

/** What a keepout (KiCad rule area) forbids: true = not allowed. */
export interface KeepoutRules {
  /** No tracks. */
  tracks?: boolean;
  /** No vias. */
  vias?: boolean;
  /** No pads. */
  pads?: boolean;
  /** No copper pours. */
  pours?: boolean;
  /** No footprints. */
  footprints?: boolean;
}

/** A pad as copper: where it is and its shape on the board, plus the footprint pad it is (``ref``/``number``). */
export interface CopperPad {
  /** Component reference (board@1 Component.ref); null when the source does not say (Gerber: inner-layer flashes take it from an outer-layer pad flashed at the same point on the same net). */
  ref: string | null;
  /** Pad number ('' for unnumbered pads). */
  number: string;
  /** Net name ('' = no net). */
  net: string;
  /** Copper layers it has copper on. */
  layers: string[];
  /** Centre of the copper shape, board frame: KiCad's pad position plus its shape offset (they differ for pads with a (drill (offset))); Gerber: the flash point. */
  at: Vec2;
  /** Degrees counter-clockwise, board frame (KiCad: the absolute pad angle). */
  rotation?: number;
  /** KiCad pad shape ('circle', 'rect', 'roundrect', 'oval', 'trapezoid', 'chamfered_rect', 'custom'), or the Gerber aperture's ('circle', 'rect', 'oval', 'polygon', or the macro name). */
  shape: string;
  /** Width, height before rotation, mm (Gerber macros: the bounding box). */
  size?: Vec2 | null;
  /** Filled loops, board frame, whose union is the pad's copper (circles and arcs flattened). */
  polygons?: Vec2[][];
  /** Hole diameter (oval: the smaller size), mm, for pads with a hole. */
  drill?: number | null;
  /** KiCad pad type, when the source says. */
  type?: "smd" | "thru_hole" | "np_thru_hole" | "connect" | null;
  /** Gerber X2 aperture function ('SMDPad,CuDef', 'ComponentPad', 'HeatsinkPad'...), when read from Gerber. */
  function?: string | null;
}

/** A net tie: a footprint whose pads short different nets on purpose (KiCad net_tie_pad_groups). */
export interface NetTie {
  /** Component reference. */
  ref: string;
  /** Pad numbers shorted together, per group. */
  groups: string[][];
  /** The nets the tie joins. */
  nets?: string[];
}

/** Pour copper of one net on one layer (teardrops excluded), for reference-plane detection. */
export interface Plane {
  /** Copper layer id. */
  layer: string;
  /** Net name. */
  net: string;
  /** Filled area, mm^2. */
  area: number;
  /** Share of the board's area (outline minus cutouts) it covers, 0..1; null without an outline. */
  coverage?: number | null;
  /** coverage >= 0.5: a solid plane, as reference planes are. */
  solid?: boolean;
}
