// Generated by `python -m boarddd.model --write` from python/src/boarddd/copper.py. Do not edit.
// The same object as schema/copper.schema.json, as an ES module (no JSON imports needed).
export default {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "boarddd/copper@1",
  "$comment": "Generated by `python -m boarddd.model --write` from python/src/boarddd/copper.py. Do not edit.",
  "title": "boarddd copper model",
  "type": "object",
  "description": "The copper of one board revision.",
  "properties": {
    "schema": {
      "description": "Format id.",
      "const": "boarddd/copper@1"
    },
    "board": {
      "description": "The board@1 document's name this copper belongs to.",
      "type": "string"
    },
    "source": {
      "description": "Provenance.",
      "$ref": "#/$defs/Source"
    },
    "units": {
      "description": "Length unit.",
      "const": "mm"
    },
    "frame": {
      "description": "Coordinate frame: x right, y up, seen from the top.",
      "const": "board"
    },
    "layers": {
      "description": "Copper layer ids, top to bottom.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "nets": {
      "description": "Net names the copper uses ('' first when some copper has no net).",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "tracks": {
      "description": "Tracks.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Track"
      },
      "default": []
    },
    "vias": {
      "description": "Vias.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Via"
      },
      "default": []
    },
    "zones": {
      "description": "Zone fills per layer (pours, teardrops, Gerber regions).",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Zone"
      },
      "default": []
    },
    "keepouts": {
      "description": "Keepouts (rule areas).",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Keepout"
      },
      "default": []
    },
    "pads": {
      "description": "Pads as copper.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/CopperPad"
      },
      "default": []
    },
    "net_ties": {
      "description": "Net ties.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/NetTie"
      },
      "default": []
    },
    "planes": {
      "description": "Pour area per layer and net, for reference-plane detection.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Plane"
      },
      "default": []
    },
    "warnings": {
      "description": "What the reader could not represent, or found suspicious (stale fills).",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "meta": {
      "description": "Free-form application data (not interpreted by boarddd).",
      "type": "object",
      "additionalProperties": {},
      "default": {}
    }
  },
  "required": [
    "schema",
    "board",
    "source",
    "units",
    "frame",
    "layers"
  ],
  "additionalProperties": false,
  "$defs": {
    "CopperPad": {
      "type": "object",
      "description": "A pad as copper: where it is and its shape on the board, plus the footprint pad it is (``ref``/``number``).",
      "properties": {
        "ref": {
          "description": "Component reference (board@1 Component.ref); null when the source does not say (Gerber: inner-layer flashes take it from an outer-layer pad flashed at the same point on the same net).",
          "type": [
            "string",
            "null"
          ]
        },
        "number": {
          "description": "Pad number ('' for unnumbered pads).",
          "type": "string"
        },
        "net": {
          "description": "Net name ('' = no net).",
          "type": "string"
        },
        "layers": {
          "description": "Copper layers it has copper on.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "at": {
          "description": "Centre of the copper shape, board frame: KiCad's pad position plus its shape offset (they differ for pads with a (drill (offset))); Gerber: the flash point.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "rotation": {
          "description": "Degrees counter-clockwise, board frame (KiCad: the absolute pad angle).",
          "type": "number",
          "default": 0.0
        },
        "shape": {
          "description": "KiCad pad shape ('circle', 'rect', 'roundrect', 'oval', 'trapezoid', 'chamfered_rect', 'custom'), or the Gerber aperture's ('circle', 'rect', 'oval', 'polygon', or the macro name).",
          "type": "string"
        },
        "size": {
          "description": "Width, height before rotation, mm (Gerber macros: the bounding box).",
          "anyOf": [
            {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "polygons": {
          "description": "Filled loops, board frame, whose union is the pad's copper (circles and arcs flattened).",
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            }
          },
          "default": []
        },
        "drill": {
          "description": "Hole diameter (oval: the smaller size), mm, for pads with a hole.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "type": {
          "description": "KiCad pad type, when the source says.",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "smd",
            "thru_hole",
            "np_thru_hole",
            "connect",
            null
          ],
          "default": null
        },
        "function": {
          "description": "Gerber X2 aperture function ('SMDPad,CuDef', 'ComponentPad', 'HeatsinkPad'...), when read from Gerber.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "ref",
        "number",
        "net",
        "layers",
        "at",
        "shape"
      ],
      "additionalProperties": false
    },
    "FillPolygon": {
      "type": "object",
      "description": "One filled area: an outer loop (counter-clockwise) minus holes (clockwise); loops implicitly closed.",
      "properties": {
        "outline": {
          "description": "Outer boundary.",
          "type": "array",
          "items": {
            "type": "array",
            "prefixItems": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "items": false,
            "minItems": 2,
            "maxItems": 2
          },
          "minItems": 3
        },
        "holes": {
          "description": "Holes inside it.",
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            "minItems": 3
          },
          "default": []
        }
      },
      "required": [
        "outline"
      ],
      "additionalProperties": false
    },
    "Keepout": {
      "type": "object",
      "description": "A keepout (KiCad rule area) on one or more copper layers.",
      "properties": {
        "layers": {
          "description": "Copper layer ids it applies to.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "outline": {
          "description": "Boundary, board frame.",
          "type": "array",
          "items": {
            "type": "array",
            "prefixItems": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "items": false,
            "minItems": 2,
            "maxItems": 2
          },
          "minItems": 3
        },
        "rules": {
          "description": "What it forbids.",
          "$ref": "#/$defs/KeepoutRules",
          "default": {
            "tracks": false,
            "vias": false,
            "pads": false,
            "pours": false,
            "footprints": false
          }
        },
        "name": {
          "description": "Rule area name, when set.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "ref": {
          "description": "The footprint (reference) it belongs to, for footprint keepouts.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "id": {
          "description": "Source id (KiCad uuid).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "layers",
        "outline"
      ],
      "additionalProperties": false
    },
    "KeepoutRules": {
      "type": "object",
      "description": "What a keepout (KiCad rule area) forbids: true = not allowed.",
      "properties": {
        "tracks": {
          "description": "No tracks.",
          "type": "boolean",
          "default": false
        },
        "vias": {
          "description": "No vias.",
          "type": "boolean",
          "default": false
        },
        "pads": {
          "description": "No pads.",
          "type": "boolean",
          "default": false
        },
        "pours": {
          "description": "No copper pours.",
          "type": "boolean",
          "default": false
        },
        "footprints": {
          "description": "No footprints.",
          "type": "boolean",
          "default": false
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "NetTie": {
      "type": "object",
      "description": "A net tie: a footprint whose pads short different nets on purpose (KiCad net_tie_pad_groups).",
      "properties": {
        "ref": {
          "description": "Component reference.",
          "type": "string"
        },
        "groups": {
          "description": "Pad numbers shorted together, per group.",
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "nets": {
          "description": "The nets the tie joins.",
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        }
      },
      "required": [
        "ref",
        "groups"
      ],
      "additionalProperties": false
    },
    "Plane": {
      "type": "object",
      "description": "Pour copper of one net on one layer (teardrops excluded), for reference-plane detection.",
      "properties": {
        "layer": {
          "description": "Copper layer id.",
          "type": "string"
        },
        "net": {
          "description": "Net name.",
          "type": "string"
        },
        "area": {
          "description": "Filled area, mm^2.",
          "type": "number",
          "minimum": 0
        },
        "coverage": {
          "description": "Share of the board's area (outline minus cutouts) it covers, 0..1; null without an outline.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "solid": {
          "description": "coverage >= 0.5: a solid plane, as reference planes are.",
          "type": "boolean",
          "default": false
        }
      },
      "required": [
        "layer",
        "net",
        "area"
      ],
      "additionalProperties": false
    },
    "Source": {
      "type": "object",
      "description": "Where the model came from (provenance).",
      "properties": {
        "kind": {
          "description": "The primary input format the reader used.",
          "type": "string",
          "enum": [
            "kicad_pcb",
            "gerber",
            "odbpp",
            "ipc2581",
            "step",
            "other"
          ]
        },
        "files": {
          "description": "Input files.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/SourceFile"
          },
          "default": []
        },
        "generator": {
          "description": "The tool that wrote the inputs, e.g. 'KiCad Pcbnew 10.0.6' (Gerber X2/gbrjob GenerationSoftware).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "reader": {
          "description": "The reader that built this model, e.g. 'boarddd 0.2.0 io.kicad'.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "created": {
          "description": "When the inputs were made (ISO 8601), if the source says.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "commit": {
          "description": "VCS commit of the design (kipr: the head sha).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "ref": {
          "description": "VCS ref or upload/package id the inputs belong to.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "kind"
      ],
      "additionalProperties": false
    },
    "SourceFile": {
      "type": "object",
      "description": "One input file the model was read from.",
      "properties": {
        "path": {
          "description": "Path relative to the source root (package, project folder or archive).",
          "type": "string"
        },
        "role": {
          "description": "What the file holds.",
          "type": "string",
          "enum": [
            "pcb",
            "copper",
            "mask",
            "paste",
            "silk",
            "outline",
            "drill",
            "drill_map",
            "fab",
            "job",
            "placement",
            "bom",
            "netlist",
            "model",
            "odb",
            "ipc2581",
            "other"
          ]
        },
        "side": {
          "description": "Board side, for layer files.",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "top",
            "bottom",
            "inner",
            "none",
            null
          ],
          "default": null
        },
        "sha256": {
          "description": "Lower-case hex SHA-256 of the file's bytes.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9a-f]{64}$",
          "default": null
        }
      },
      "required": [
        "path",
        "role"
      ],
      "additionalProperties": false
    },
    "Track": {
      "type": "object",
      "description": "A routed track: a straight segment, or an arc through ``mid``; round ends of diameter ``width``.",
      "properties": {
        "layer": {
          "description": "Copper layer id ('F.Cu', 'In1.Cu').",
          "type": "string"
        },
        "net": {
          "description": "Net name ('' = no net).",
          "type": "string"
        },
        "width": {
          "description": "Track width, mm.",
          "type": "number",
          "minimum": 0
        },
        "start": {
          "description": "First end, board frame.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "end": {
          "description": "Second end, board frame.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "mid": {
          "description": "Arcs: the point on the arc halfway between start and end (KiCad's (mid)); null for a straight segment.",
          "anyOf": [
            {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "id": {
          "description": "Source id (KiCad uuid), when the source has one.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "layer",
        "net",
        "width",
        "start",
        "end"
      ],
      "additionalProperties": false
    },
    "Via": {
      "type": "object",
      "description": "A plated via joining copper layers ``span[0]`` to ``span[1]`` (top to bottom).",
      "properties": {
        "at": {
          "description": "Centre, board frame.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "net": {
          "description": "Net name ('' = no net).",
          "type": "string"
        },
        "diameter": {
          "description": "Pad (annular ring) diameter, mm: the largest when it differs per layer.",
          "type": "number",
          "minimum": 0
        },
        "drill": {
          "description": "Finished hole diameter, mm; 0 when the source has none (Gerber without drill files) or writes a placeholder.",
          "type": "number",
          "minimum": 0
        },
        "span": {
          "description": "First and last copper layer the hole connects, top to bottom.",
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "type": {
          "description": "From the span ('through': outer to outer) or the source's own type (KiCad blind/micro).",
          "type": "string",
          "enum": [
            "through",
            "blind",
            "buried",
            "micro"
          ]
        },
        "pad_layers": {
          "description": "Layers in the span with an annular ring, when not all (KiCad 'remove unused layers', Gerber); null = all.",
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "padstack": {
          "description": "Per-layer pad diameters, when they differ from ``diameter``.",
          "anyOf": [
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/ViaPad"
              }
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "id": {
          "description": "Source id (KiCad uuid).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "at",
        "net",
        "diameter",
        "drill",
        "span",
        "type"
      ],
      "additionalProperties": false
    },
    "ViaPad": {
      "type": "object",
      "description": "A via's annular ring on one layer, when it differs from the via's default (KiCad 10 padstacks, Gerber).",
      "properties": {
        "layer": {
          "description": "Copper layer id.",
          "type": "string"
        },
        "diameter": {
          "description": "Pad diameter on this layer, mm.",
          "type": "number",
          "minimum": 0
        }
      },
      "required": [
        "layer",
        "diameter"
      ],
      "additionalProperties": false
    },
    "Zone": {
      "type": "object",
      "description": "Copper of one zone (pour) on one layer: a multi-layer zone has one entry per layer, sharing ``id``.",
      "properties": {
        "layer": {
          "description": "Copper layer id.",
          "type": "string"
        },
        "net": {
          "description": "Net name ('' = no net).",
          "type": "string"
        },
        "kind": {
          "description": "'pour': a KiCad zone; 'teardrop': a KiCad teardrop zone; 'shape': a filled copper drawing (KiCad gr_/fp_ polygons, rectangles, circles on copper; Gerber EtchedComponent regions); 'region': other filled copper from a Gerber/ODB++ region, which does not say what drew it.",
          "type": "string",
          "enum": [
            "pour",
            "teardrop",
            "shape",
            "region"
          ]
        },
        "fill": {
          "description": "The filled copper as the source stores it (may be stale: see ``stale``).",
          "type": "array",
          "items": {
            "$ref": "#/$defs/FillPolygon"
          }
        },
        "area": {
          "description": "Filled area, mm^2 (outlines minus holes).",
          "type": "number",
          "minimum": 0
        },
        "outline": {
          "description": "The zone's own boundary as drawn (KiCad (polygon)); null for regions.",
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "array",
                "prefixItems": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  }
                ],
                "items": false,
                "minItems": 2,
                "maxItems": 2
              }
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "priority": {
          "description": "KiCad zone priority (higher fills first).",
          "type": [
            "integer",
            "null"
          ],
          "default": null
        },
        "name": {
          "description": "Zone name, when set.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "filled": {
          "description": "False when the zone has no fill at all on this layer (never filled, or filled before it was moved).",
          "type": "boolean",
          "default": true
        },
        "stale": {
          "description": "True when a fill check found the fill out of date (copper of another net inside it); null = not checked.",
          "type": [
            "boolean",
            "null"
          ],
          "default": null
        },
        "id": {
          "description": "Source id (KiCad zone uuid), shared by a multi-layer zone's entries.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "layer",
        "net",
        "kind",
        "fill",
        "area"
      ],
      "additionalProperties": false
    }
  }
};
