// Generated by `python -m boarddd.model --write` from python/src/boarddd/impedance/result.py. Do not edit.
// The same object as schema/impedance.schema.json, as an ES module (no JSON imports needed).
export default {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "boarddd/impedance@1",
  "$comment": "Generated by `python -m boarddd.model --write` from python/src/boarddd/impedance/result.py. Do not edit.",
  "title": "boarddd impedance analysis",
  "type": "object",
  "description": "Impedance along one net's (or a differential pair's) route.",
  "properties": {
    "schema": {
      "description": "Format id.",
      "const": "boarddd/impedance@1"
    },
    "board": {
      "description": "The board@1 document's name.",
      "type": "string"
    },
    "nets": {
      "description": "The net, or the pair [p, n].",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 2
    },
    "kind": {
      "description": "A net or a pair.",
      "type": "string",
      "enum": [
        "single",
        "differential"
      ]
    },
    "solver": {
      "description": "The solver asked for (tier 1 falls back to tier 2 where it has none).",
      "type": "string",
      "enum": [
        "field",
        "closedform"
      ]
    },
    "target": {
      "description": "The target; null when there is none.",
      "anyOf": [
        {
          "$ref": "#/$defs/Target"
        },
        {
          "type": "null"
        }
      ]
    },
    "sections": {
      "description": "The route in sections, in route order (a pair's uncoupled second net last).",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Section"
      }
    },
    "summary": {
      "description": "Length-weighted summary.",
      "$ref": "#/$defs/Summary"
    },
    "discontinuities": {
      "description": "Changes along the route.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Discontinuity"
      },
      "default": []
    },
    "options": {
      "description": "The options the analysis ran with.",
      "type": "object",
      "additionalProperties": {},
      "default": {}
    },
    "warnings": {
      "description": "Defaults used, unsolvable sections, target kind mismatches.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "timing": {
      "description": "Timing.",
      "$ref": "#/$defs/Timing"
    }
  },
  "required": [
    "schema",
    "board",
    "nets",
    "kind",
    "solver",
    "target",
    "sections",
    "summary",
    "timing"
  ],
  "additionalProperties": false,
  "$defs": {
    "Discontinuity": {
      "type": "object",
      "description": "A change along the route, at its position.",
      "properties": {
        "type": {
          "description": "What changes.",
          "type": "string",
          "enum": [
            "via",
            "ref_change",
            "width_change",
            "plane_gap",
            "no_ref",
            "uncoupled",
            "ref_edge"
          ]
        },
        "at": {
          "description": "Where, board frame.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "s": {
          "description": "Distance along the route, mm.",
          "type": "number"
        },
        "layer": {
          "description": "Copper layer after the change.",
          "type": "string"
        },
        "net": {
          "description": "Net.",
          "type": "string"
        },
        "detail": {
          "description": "Human-readable detail.",
          "type": "string",
          "default": ""
        }
      },
      "required": [
        "type",
        "at",
        "s",
        "layer",
        "net"
      ],
      "additionalProperties": false
    },
    "Reference": {
      "type": "object",
      "description": "A reference plane under (bottom) or over (top) a section.",
      "properties": {
        "side": {
          "description": "Above or below the trace.",
          "type": "string",
          "enum": [
            "top",
            "bottom"
          ]
        },
        "layer": {
          "description": "Copper layer id of the plane.",
          "type": "string"
        },
        "net": {
          "description": "The plane's net ('' when unknown).",
          "type": "string"
        },
        "h": {
          "description": "Dielectric height from the trace's layer, mm.",
          "type": "number",
          "minimum": 0
        },
        "extent": {
          "description": "Where the plane ends across the trace, relative to its centre line (mm, quantised); null: beyond the window.",
          "type": "array",
          "prefixItems": [
            {
              "type": [
                "number",
                "null"
              ]
            },
            {
              "type": [
                "number",
                "null"
              ]
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "skipped": {
          "description": "Nearer copper layers with no plane under the trace (a split, a void, or a signal layer).",
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        }
      },
      "required": [
        "side",
        "layer",
        "net",
        "h",
        "extent"
      ],
      "additionalProperties": false
    },
    "Section": {
      "type": "object",
      "description": "A stretch of the route with one cross-section.",
      "properties": {
        "net": {
          "description": "The net it belongs to (a pair's coupled stretches are the first net's).",
          "type": "string"
        },
        "start": {
          "description": "Where it starts, board frame.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "end": {
          "description": "Where it ends, board frame.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "s0": {
          "description": "Distance along the route where it starts, mm.",
          "type": "number",
          "minimum": 0
        },
        "s1": {
          "description": "Distance along the route where it ends, mm.",
          "type": "number",
          "minimum": 0
        },
        "length": {
          "description": "mm.",
          "type": "number",
          "minimum": 0
        },
        "layer": {
          "description": "Copper layer id.",
          "type": "string"
        },
        "structure": {
          "description": "The transmission-line structure (classified, or overridden).",
          "type": "string",
          "enum": [
            "microstrip",
            "embedded_microstrip",
            "stripline",
            "offset_stripline",
            "cpw",
            "cpwg",
            "none"
          ]
        },
        "kind": {
          "description": "'differential' where a pair is edge-coupled.",
          "type": "string",
          "enum": [
            "single",
            "differential"
          ]
        },
        "geometry": {
          "description": "The cross-section.",
          "$ref": "#/$defs/SectionGeometry"
        },
        "z": {
          "description": "Its impedance; null when it has none (no reference plane, or not solvable).",
          "anyOf": [
            {
              "$ref": "#/$defs/SectionZ"
            },
            {
              "type": "null"
            }
          ]
        },
        "refs": {
          "description": "Reference planes.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/Reference"
          },
          "default": []
        },
        "flags": {
          "description": "no_ref: no reference plane (no Z); plane_gap: a plane is split or voided under the trace; ref_edge: the plane ends within the margin; neighbour: another signal within the coplanar window; uncoupled: a pair's line away from its partner; overlap: other copper overlaps the trace; override: set by the caller; solver_error.",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "no_ref",
              "plane_gap",
              "ref_edge",
              "neighbour",
              "uncoupled",
              "overlap",
              "override",
              "solver_error"
            ]
          },
          "default": []
        },
        "tracks": {
          "description": "Ids (copper@1 Track.id) of the tracks it covers.",
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        }
      },
      "required": [
        "net",
        "start",
        "end",
        "s0",
        "s1",
        "length",
        "layer",
        "structure",
        "kind",
        "geometry",
        "z"
      ],
      "additionalProperties": false
    },
    "SectionGeometry": {
      "type": "object",
      "description": "The cross-section as found on the board (mm); gaps are edge to edge, quantised as solved.",
      "properties": {
        "width": {
          "description": "Track width.",
          "type": "number",
          "minimum": 0
        },
        "thickness": {
          "description": "Copper thickness (stackup).",
          "type": "number",
          "minimum": 0
        },
        "partner_width": {
          "description": "Pairs: the partner's width.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "gap": {
          "description": "Pairs: the gap to the partner.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "coplanar_gap": {
          "description": "Gap to the coplanar ground on the left and right (seen along the route); null: none within the window.",
          "type": "array",
          "prefixItems": [
            {
              "type": [
                "number",
                "null"
              ]
            },
            {
              "type": [
                "number",
                "null"
              ]
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "h_top": {
          "description": "Dielectric height to the reference plane above.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "h_bottom": {
          "description": "Dielectric height to the reference plane below.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "width",
        "thickness",
        "coplanar_gap"
      ],
      "additionalProperties": false
    },
    "SectionZ": {
      "type": "object",
      "description": "The impedance of a section's cross-section.",
      "properties": {
        "Z0": {
          "description": "Single-ended characteristic impedance, ohms.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "Zdiff": {
          "description": "Differential impedance, ohms (an uncoupled stretch of a pair: 2 Z0, its two lines independent).",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "Zcommon": {
          "description": "Common-mode impedance, ohms.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "Zodd": {
          "description": "Odd-mode impedance, ohms.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "Zeven": {
          "description": "Even-mode impedance, ohms.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "eps_eff": {
          "description": "Effective dielectric constant (single-ended).",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "error_pct": {
          "description": "The field solver's error estimate, percent; null for closed form.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "solver": {
          "description": "Tier 2 (field solver) or tier 1 (closed form).",
          "type": "string",
          "enum": [
            "field",
            "closedform"
          ]
        },
        "model": {
          "description": "The closed-form model, for tier 1.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "solver"
      ],
      "additionalProperties": false
    },
    "Summary": {
      "type": "object",
      "description": "The route's impedance weighted by length (the first net of a pair).",
      "properties": {
        "key": {
          "description": "What is summarised.",
          "type": "string",
          "enum": [
            "Z0",
            "Zdiff"
          ]
        },
        "length": {
          "description": "Route length, mm.",
          "type": "number",
          "minimum": 0
        },
        "length_with_z": {
          "description": "Length with an impedance, mm.",
          "type": "number",
          "minimum": 0
        },
        "z_weighted": {
          "description": "Length-weighted mean, ohms.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "z_min": {
          "description": "Lowest section value, ohms.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "z_max": {
          "description": "Highest section value, ohms.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "out_of_tolerance_length": {
          "description": "Length outside the target's tolerance, mm; null without a target.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "out_of_tolerance_pct": {
          "description": "Share of the route outside tolerance or without an impedance, percent; null without a target.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "within": {
          "description": "Every section has an impedance within tolerance; null without a target.",
          "type": [
            "boolean",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "key",
        "length",
        "length_with_z"
      ],
      "additionalProperties": false
    },
    "Target": {
      "type": "object",
      "description": "The impedance the route is checked against.",
      "properties": {
        "value": {
          "description": "Ohms.",
          "type": "number",
          "exclusiveMinimum": 0
        },
        "key": {
          "description": "What it applies to: Z0 for a net, Zdiff for a pair.",
          "type": "string",
          "enum": [
            "Z0",
            "Zdiff"
          ]
        },
        "tolerance_pct": {
          "description": "Allowed deviation, percent (the analysis's default when the target gives none).",
          "type": "number"
        },
        "source": {
          "description": "The net class's ImpedanceTarget, or the caller's.",
          "type": "string",
          "enum": [
            "net_class",
            "option"
          ]
        },
        "net_class": {
          "description": "The net class it comes from.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "value",
        "key",
        "tolerance_pct",
        "source"
      ],
      "additionalProperties": false
    },
    "Timing": {
      "type": "object",
      "description": "How long the analysis took.",
      "properties": {
        "ms": {
          "description": "Wall time, ms.",
          "type": "number",
          "minimum": 0
        },
        "solve_ms": {
          "description": "Of which solving cross-sections, ms.",
          "type": "number",
          "minimum": 0
        },
        "stations": {
          "description": "Stations cut.",
          "type": "integer",
          "minimum": 0
        },
        "solves": {
          "description": "Cross-sections solved (distinct geometries not in the cache).",
          "type": "integer",
          "minimum": 0
        },
        "cache_hits": {
          "description": "Sections whose cross-section was already solved.",
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "ms",
        "solve_ms",
        "stations",
        "solves",
        "cache_hits"
      ],
      "additionalProperties": false
    }
  }
};
