// Generated by `python -m boarddd.model --write` from python/src/boarddd/model.py. Do not edit.
// The boarddd/board@1 model; see docs/model.md.

export type SchemaId = "boarddd/board@1";
/** x, y in mm. */
export type Vec2 = [number, number];
export type Vec3 = [number, number, number];

/** One board revision. */
export interface Board {
  /** Format id. */
  schema: "boarddd/board@1";
  /** Board name (project or file stem). */
  name: string;
  /** Design revision as the source states it. */
  revision?: string | null;
  /** Provenance. */
  source: Source;
  /** Length unit. */
  units: "mm";
  /** Coordinate frame: x right, y up, seen from the top. */
  frame: "board";
  /** Source origins (board frame). */
  origin?: Origin;
  /** Board edge; null when the source has none. */
  outline?: Outline | null;
  /** Build: thickness, finish, colours, physical layers. */
  stackup?: Stackup;
  /** Drawable layers. */
  layers?: Layer[];
  /** Holes. */
  drills?: Drill[];
  /** Footprint definitions by library id. */
  footprints?: Record<string, Footprint>;
  /** Placed parts. */
  components?: Component[];
  /** Panel, when the source is one. */
  panel?: Panel | null;
  /** Nets, when the source has them (KiCad, ODB++, IPC-2581, Gerber X2). */
  nets?: Net[];
  /** Net classes with their rules and impedance targets. */
  net_classes?: NetClass[];
  /** What the reader could not represent or had to guess. */
  warnings?: string[];
  /** Free-form application data (not interpreted by boarddd). */
  meta?: Record<string, unknown>;
}

/** Where the model came from (provenance). */
export interface Source {
  /** The primary input format the reader used. */
  kind: "kicad_pcb" | "gerber" | "odbpp" | "ipc2581" | "step" | "other";
  /** Input files. */
  files?: SourceFile[];
  /** The tool that wrote the inputs, e.g. 'KiCad Pcbnew 10.0.6' (Gerber X2/gbrjob GenerationSoftware). */
  generator?: string | null;
  /** The reader that built this model, e.g. 'boarddd 0.2.0 io.kicad'. */
  reader?: string | null;
  /** When the inputs were made (ISO 8601), if the source says. */
  created?: string | null;
  /** VCS commit of the design (kipr: the head sha). */
  commit?: string | null;
  /** VCS ref or upload/package id the inputs belong to. */
  ref?: string | null;
}

/** One input file the model was read from. */
export interface SourceFile {
  /** Path relative to the source root (package, project folder or archive). */
  path: string;
  /** What the file holds. */
  role: "pcb" | "copper" | "mask" | "paste" | "silk" | "outline" | "drill" | "drill_map" | "fab" | "job" | "placement" | "bom" | "netlist" | "model" | "odb" | "ipc2581" | "other";
  /** Board side, for layer files. */
  side?: "top" | "bottom" | "inner" | "none" | null;
  /** Lower-case hex SHA-256 of the file's bytes. */
  sha256?: string | null;
}

/** Origins the source defines besides the file origin, in the board frame, so writers can go back. */
export interface Origin {
  /** Auxiliary (place/drill-file) origin, e.g. KiCad's aux_axis_origin. */
  aux?: Vec2 | null;
  /** Grid origin. */
  grid?: Vec2 | null;
  /** Origin the drill files were written relative to, when not the file origin. */
  drill?: Vec2 | null;
}

/** The board shape: arcs flattened to polylines, loops implicitly closed (last point != first). */
export interface Outline {
  /** The outer edge, counter-clockwise. */
  board: Vec2[];
  /** Internal cutouts (routed holes, slots wider than a drill), clockwise. */
  cutouts?: Vec2[][];
  /** True when the edge is a fallback (bounding box, convex hull) rather than the real profile. */
  approximate?: boolean;
}

/** Board build: thickness, finish, colours, copper count and the physical layers. */
export interface Stackup {
  /** Finished board thickness, mm. */
  thickness?: number | null;
  /** Number of copper layers. */
  copper_layers?: number | null;
  /** Surface finish as the source names it ('ENIG', 'HASL', 'OSP', 'None'...). */
  finish?: string | null;
  /** Solder mask colour per side. */
  mask_color?: SideValues;
  /** Silkscreen colour per side. */
  silk_color?: SideValues;
  /** Physical layers top to bottom; empty when the source has no stackup. */
  layers?: StackupLayer[];
  /** The board is ordered impedance controlled (KiCad dielectric_constraints, gbrjob ImpedanceControlled). */
  impedance_controlled?: boolean | null;
}

/** A value per board side. */
export interface SideValues {
  /** Top side. */
  top?: string | null;
  /** Bottom side. */
  bottom?: string | null;
}

/** One physical layer, listed top to bottom. */
export interface StackupLayer {
  /** Source name: 'F.Cu', 'dielectric 1', 'Top Solder Mask'... */
  name: string;
  /** Material role. */
  kind: "silk" | "paste" | "mask" | "copper" | "dielectric" | "other";
  /** 'inner' for inner copper and dielectrics. */
  side: "top" | "bottom" | "inner" | "none";
  /** mm (with sublayers: their sum). */
  thickness?: number | null;
  /** 'FR4', 'Polyimide'... (with sublayers of different materials: their names joined by ' + '). */
  material?: string | null;
  /** Colour as the source names it: a name ('Blue', 'Matte Black') or '#RRGGBB'. */
  color?: string | null;
  /** Dielectric constant (with sublayers: the series value, total thickness / sum(thickness_i / epsilon_r_i)). */
  epsilon_r?: number | null;
  /** Dielectric loss tangent (with sublayers: the thickness-weighted mean). */
  loss_tangent?: number | null;
  /** The Layer.id this physical layer is drawn by, if any. */
  layer?: string | null;
  /** Dielectrics: prepreg or core, when the source says (KiCad type, IPC-2581 DIELPREG/DIELCORE). */
  dielectric?: "prepreg" | "core" | null;
  /** Dielectrics the source splits into parts, top to bottom, the first included; empty otherwise. */
  sublayers?: StackupSublayer[];
  /** Hz at which epsilon_r and loss_tangent are given (KiCad spec_frequency, ODB++ FrequencyVal). */
  frequency?: number | null;
  /** How epsilon_r/loss_tangent vary with frequency (KiCad dielectric_model). */
  dielectric_model?: "constant" | "djordjevic_sarkar" | null;
  /** Thickness fixed for impedance control (KiCad '(thickness ... locked)'). */
  locked?: boolean | null;
  /** Manufacturing tolerances, when the source gives them. */
  tolerance?: Tolerance | null;
  /** Copper: plated (finished) thickness, mm, when it differs from the base foil. */
  finished_thickness?: number | null;
  /** Copper: RMS surface roughness, mm (0.0005 = 0.5 um). */
  roughness_rq?: number | null;
  /** Copper: conductivity, S/m. */
  conductivity?: number | null;
  /** Copper: etch factor (thickness / one side's undercut), for trapezoidal traces. */
  etch_factor?: number | null;
  /** Solder mask: thickness over the traces, mm, when it differs from 'thickness' (over the laminate). */
  thickness_over_copper?: number | null;
}

/** One part of a dielectric the source splits into several (KiCad ``addsublayer``, gbrjob '(1/2)' entries). */
export interface StackupSublayer {
  /** mm. */
  thickness?: number | null;
  /** Material name, e.g. '2116 RC58%'. */
  material?: string | null;
  /** Colour as the source names it. */
  color?: string | null;
  /** Dielectric constant. */
  epsilon_r?: number | null;
  /** Dielectric loss tangent. */
  loss_tangent?: number | null;
}

/** Manufacturing tolerances of a stackup layer, as [minus, plus] deviations (IPC-2581 tolPlus/tolMinus). */
export interface Tolerance {
  /** [minus, plus] in mm, e.g. [-0.01, 0.01]. */
  thickness?: Vec2 | null;
  /** [minus, plus] of the dielectric constant. */
  epsilon_r?: Vec2 | null;
}

/** One drawable layer (a Gerber, an ODB++ layer, a drill file...). */
export interface Layer {
  /** Unique id; KiCad canonical names where they apply ('F.Cu', 'In1.Cu', 'Edge.Cuts', 'PTH'). */
  id: string;
  /** What the layer is. */
  role: "copper" | "mask" | "paste" | "silk" | "outline" | "drill" | "fab" | "courtyard" | "adhesive" | "user" | "other";
  /** Board side; 'none' for outline/drill/user layers. */
  side: "top" | "bottom" | "inner" | "none";
  /** Stack position: copper 1..N top to bottom (Gerber L<n>); other layers ascend in drawing order. */
  order: number;
  /** SourceFile paths that draw this layer (usually one). */
  files?: string[];
  /** Format of the files. */
  format?: "gerber" | "excellon" | "odb" | "ipc2581" | "svg" | "other";
  /** Gerber X2 file polarity. */
  polarity?: "positive" | "negative";
  /** Raw Gerber X2 %TF.FileFunction (or ODB++ layer type). */
  function?: string | null;
  /** Drill layers: plated (PTH) or not (NPTH); null when mixed. */
  plated?: boolean | null;
}

/** A hole in the board frame: round when x2/y2 are null, otherwise a slot from (x, y) to (x2, y2). */
export interface Drill {
  /** Centre (slot: first end), mm. */
  x: number;
  /** Centre (slot: first end), mm. */
  y: number;
  /** Finished hole diameter (slot: width), mm; 0 when the source writes a placeholder. */
  diameter: number;
  /** Plated through hole. */
  plated: boolean;
  /** Slot: second end. */
  x2?: number | null;
  /** Slot: second end. */
  y2?: number | null;
  /** Excellon tool, e.g. 'T3'. */
  tool?: string | null;
  /** Gerber X2 drill function. */
  function?: "via" | "component" | "mechanical" | null;
  /** Filled/capped via (not punched in 3D). */
  filled?: boolean;
  /** The drill Layer.id this hole comes from. */
  layer?: string | null;
}

/** A footprint definition, shared by components that use it (library orientation, top side). */
export interface Footprint {
  /** Library id, e.g. 'Resistor_SMD:R_0603_1608Metric' (the key in Board.footprints). */
  name: string;
  /** Pads. */
  pads?: Pad[];
  /** Silk/fab/courtyard drawings. */
  graphics?: Graphic[];
  /** KiCad footprint attributes as written in the library ('smd', 'through_hole', ...). */
  attr?: string[];
}

/** boarddd's JS Pad (src/geom/pads.js, checked against pcbnew) plus magpie's extra fields. */
export interface Pad {
  /** Pad number/name ('' for unnumbered pads). */
  number: string;
  /** KiCad pad type. */
  type: "smd" | "thru_hole" | "np_thru_hole" | "connect";
  /** KiCad pad shape. */
  shape: "circle" | "rect" | "oval" | "roundrect" | "chamfered_rect" | "trapezoid" | "custom";
  /** x, y (footprint frame, y down) and rotation in degrees relative to the footprint. */
  at: Vec3;
  /** Width, height, mm. */
  size: Vec2;
  /** KiCad layer names, wildcards kept ('*.Cu', 'F.Paste'...). */
  layers: string[];
  /** The hole, for thru_hole/np_thru_hole. */
  drill?: PadDrill | null;
  /** Copper shape offset of a pad without a hole (castellated SMD pads); pads with one keep it in drill.offset. */
  offset?: Vec2 | null;
  /** roundrect/chamfered: corner radius / shorter side. */
  roundrect_rratio?: number | null;
  /** chamfered_rect: chamfer / shorter side. */
  chamfer_ratio?: number | null;
  /** chamfered_rect: which corners. */
  chamfer?: ("top_left" | "top_right" | "bottom_left" | "bottom_right")[] | null;
  /** trapezoid: KiCad rect_delta. */
  rect_delta?: Vec2 | null;
  /** custom: anchor shape. */
  anchor?: "circle" | "rect" | null;
  /** custom: primitives as filled loops, pad-local. */
  primitives?: Primitive[] | null;
  /** Pad mask expansion override, mm. */
  solder_mask_margin?: number | null;
  /** Pad paste expansion override, mm. */
  solder_paste_margin?: number | null;
  /** Pad function/net role when the source says ('ground', 'heatsink', 'fiducial'...). */
  function?: string | null;
  /** Paste openings when they differ from the copper; null = unknown/as copper, [] = no paste. */
  paste?: Aperture[] | null;
  /** Mask opening when it differs from copper + margin. */
  mask?: Aperture | null;
  /** Extra holes (rare; multi-drill pads from ODB++/IPC-2581). */
  holes?: PadDrill[] | null;
}

/** A pad's hole; an oval hole runs along its long axis. */
export interface PadDrill {
  /** Hole shape. */
  shape: "circle" | "oval";
  /** Width, height (circle: both the diameter), mm. */
  size: Vec2;
  /** Copper offset relative to the hole (KiCad (drill (offset)) semantics). */
  offset?: Vec2;
}

/** A custom-pad primitive flattened to a filled loop, pad-local. */
export interface Primitive {
  /** Loop points. */
  pts: Vec2[];
}

/** A mask or paste opening when it differs from the copper (magpie Aperture). */
export interface Aperture {
  /** Opening shape. */
  shape: "rect" | "roundrect" | "circle" | "oval" | "polygon";
  /** Width, height, mm. */
  size: Vec2;
  /** Pad-local centre. */
  center?: Vec2;
  /** Degrees, relative to the pad. */
  rotation?: number;
  /** Corner radius / shorter side. */
  roundrect_ratio?: number | null;
  /** Pad-local outline, for 'polygon'. */
  polygon?: Vec2[] | null;
}

/** A footprint drawing (silk, fab, courtyard): arcs/circles flattened, footprint frame. */
export interface Graphic {
  /** KiCad layer name ('F.SilkS', 'F.Fab', 'F.CrtYd'...). */
  layer: string;
  /** Original primitive. */
  kind: "line" | "rect" | "circle" | "arc" | "poly" | "curve";
  /** Points. */
  pts: Vec2[];
  /** Stroke width, mm (0 for filled-only). */
  width: number;
  /** Closed loop. */
  closed?: boolean;
  /** Filled. */
  filled?: boolean;
}

/** A placed part. */
export interface Component {
  /** Reference designator. */
  ref: string;
  /** Mounting side. */
  side: "top" | "bottom";
  /** Footprint origin, board frame, mm. */
  x: number;
  /** Footprint origin, board frame, mm. */
  y: number;
  /** Degrees counter-clockwise seen from the top, as KiCad stores the footprint orientation and its pos file prints it (bottom parts too; see docs/model.md for the placement transform). */
  rotation: number;
  /** Value field. */
  value?: string | null;
  /** Footprint name: a key in Board.footprints when present, else the source's name. */
  footprint?: string | null;
  /** Assembly technology. */
  mount?: "smd" | "tht" | "other" | null;
  /** False for DNP (do not populate). */
  populate?: boolean;
  /** Listed in the BOM. */
  in_bom?: boolean;
  /** Listed in placement (pick-and-place) files. */
  in_pos?: boolean;
  /** Manufacturer part numbers (alternates allowed). */
  mpn?: PartNumber[];
  /** 3D models. */
  models?: ModelRef[];
  /** Body height above the board, mm, when known. */
  height?: number | null;
  /** Other source fields (KiCad properties, BOM columns). */
  attributes?: Record<string, string>;
}

/** A manufacturer part number. */
export interface PartNumber {
  /** Manufacturer part number. */
  mpn: string;
  /** Manufacturer. */
  manufacturer?: string | null;
}

/** A 3D model placed on a component (KiCad (model ...) semantics). */
export interface ModelRef {
  /** Model path as the source writes it (env vars like ${KICAD9_3DMODEL_DIR} kept). */
  path: string;
  /** mm, footprint frame (KiCad 3D viewer: x right, y up, z up). */
  offset?: Vec3;
  /** Degrees about x, y, z. */
  rotate?: Vec3;
  /** Scale. */
  scale?: Vec3;
  /** Hidden in the 3D view. */
  hide?: boolean;
}

/** Panelisation, when the source is a panel of identical boards. */
export interface Panel {
  /** Board copies. */
  instances?: PanelInstance[];
}

/** One board copy in a panel, board frame of the panel. */
export interface PanelInstance {
  /** Offset, mm. */
  x: number;
  /** Offset, mm. */
  y: number;
  /** Degrees counter-clockwise. */
  rotation?: number;
}

/** An electrical net. */
export interface Net {
  /** Net name as the source writes it ('/USB/D+', 'GND'). */
  name: string;
  /** The NetClass.name it belongs to ('Default' when the source assigns none). */
  net_class?: string | null;
  /** The partner net of a differential pair (KiCad pairs '+'/'-' and 'P'/'N' suffixes). */
  pair?: string | null;
}

/** A net class (KiCad .kicad_pro net_settings) with its design rules and impedance target. */
export interface NetClass {
  /** Class name. */
  name: string;
  /** Net names in the class. */
  nets?: string[];
  /** Assignment patterns (KiCad netclass_patterns, wildcards). */
  patterns?: string[];
  /** mm. */
  track_width?: number | null;
  /** mm. */
  clearance?: number | null;
  /** mm. */
  diff_pair_width?: number | null;
  /** mm. */
  diff_pair_gap?: number | null;
  /** mm. */
  via_diameter?: number | null;
  /** mm. */
  via_drill?: number | null;
  /** KiCad priority (lower wins; Default is the largest). */
  priority?: number | null;
  /** KiCad 10 tuning profile name, when set. */
  tuning_profile?: string | null;
  /** Controlled-impedance target, when known. */
  impedance?: ImpedanceTarget | null;
}

/** A controlled-impedance target. */
export interface ImpedanceTarget {
  /** Single-ended Z0 or differential Zdiff. */
  kind: "single" | "differential";
  /** Ohms. */
  target: number;
  /** Allowed deviation, percent (10 = +-10 %); null = unspecified. */
  tolerance_pct?: number | null;
  /** Differential: common-mode target, ohms, when given (class names like BAL_D90_C30). */
  common_mode?: number | null;
  /** Transmission-line structure, when the source says (MS, SL, CPW, CPWG). */
  structure?: "microstrip" | "stripline" | "coplanar" | "coplanar_grounded" | null;
  /** Where the target comes from: a KiCad tuning profile, an IPC-2581/ODB++ spec, the class name convention (SE_50_CP, DP_90_MS, 90ohm...) or a user entry. */
  source: "tuning_profile" | "ipc2581" | "odbpp" | "name" | "user";
  /** Per-layer geometry, when the source gives it. */
  layers?: ImpedanceLayer[];
}

/** Geometry a target applies to on one signal layer (KiCad tuning profile layer entry, IPC-2581 Impedance). */
export interface ImpedanceLayer {
  /** Signal layer ('F.Cu', 'In1.Cu'). */
  layer: string;
  /** Track width, mm. */
  width?: number | null;
  /** Differential pair gap, mm. */
  gap?: number | null;
  /** Reference plane above, if any. */
  ref_top?: string | null;
  /** Reference plane below, if any. */
  ref_bottom?: string | null;
}
