// Generated by `python -m boarddd.model --write` from python/src/boarddd/model.py. Do not edit.
// The same object as schema/board.schema.json, as an ES module (no JSON imports needed).
export default {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "boarddd/board@1",
  "$comment": "Generated by `python -m boarddd.model --write` from python/src/boarddd/model.py. Do not edit.",
  "title": "boarddd board model",
  "type": "object",
  "description": "One board revision.",
  "properties": {
    "schema": {
      "description": "Format id.",
      "const": "boarddd/board@1"
    },
    "name": {
      "description": "Board name (project or file stem).",
      "type": "string"
    },
    "revision": {
      "description": "Design revision as the source states it.",
      "type": [
        "string",
        "null"
      ],
      "default": null
    },
    "source": {
      "description": "Provenance.",
      "$ref": "#/$defs/Source"
    },
    "units": {
      "description": "Length unit.",
      "const": "mm"
    },
    "frame": {
      "description": "Coordinate frame: x right, y up, seen from the top.",
      "const": "board"
    },
    "origin": {
      "description": "Source origins (board frame).",
      "$ref": "#/$defs/Origin",
      "default": {
        "aux": null,
        "grid": null,
        "drill": null
      }
    },
    "outline": {
      "description": "Board edge; null when the source has none.",
      "anyOf": [
        {
          "$ref": "#/$defs/Outline"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "stackup": {
      "description": "Build: thickness, finish, colours, physical layers.",
      "$ref": "#/$defs/Stackup",
      "default": {
        "thickness": null,
        "copper_layers": null,
        "finish": null,
        "mask_color": {
          "top": null,
          "bottom": null
        },
        "silk_color": {
          "top": null,
          "bottom": null
        },
        "layers": [],
        "impedance_controlled": null
      }
    },
    "layers": {
      "description": "Drawable layers.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Layer"
      },
      "default": []
    },
    "drills": {
      "description": "Holes.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Drill"
      },
      "default": []
    },
    "footprints": {
      "description": "Footprint definitions by library id.",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/Footprint"
      },
      "default": {}
    },
    "components": {
      "description": "Placed parts.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Component"
      },
      "default": []
    },
    "panel": {
      "description": "Panel, when the source is one.",
      "anyOf": [
        {
          "$ref": "#/$defs/Panel"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "nets": {
      "description": "Nets, when the source has them (KiCad, ODB++, IPC-2581, Gerber X2).",
      "type": "array",
      "items": {
        "$ref": "#/$defs/Net"
      },
      "default": []
    },
    "net_classes": {
      "description": "Net classes with their rules and impedance targets.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/NetClass"
      },
      "default": []
    },
    "warnings": {
      "description": "What the reader could not represent or had to guess.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "meta": {
      "description": "Free-form application data (not interpreted by boarddd).",
      "type": "object",
      "additionalProperties": {},
      "default": {}
    }
  },
  "required": [
    "schema",
    "name",
    "source",
    "units",
    "frame"
  ],
  "additionalProperties": false,
  "$defs": {
    "Aperture": {
      "type": "object",
      "description": "A mask or paste opening when it differs from the copper (magpie Aperture).",
      "properties": {
        "shape": {
          "description": "Opening shape.",
          "type": "string",
          "enum": [
            "rect",
            "roundrect",
            "circle",
            "oval",
            "polygon"
          ]
        },
        "size": {
          "description": "Width, height, mm.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "center": {
          "description": "Pad-local centre.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2,
          "default": [
            0.0,
            0.0
          ]
        },
        "rotation": {
          "description": "Degrees, relative to the pad.",
          "type": "number",
          "default": 0.0
        },
        "roundrect_ratio": {
          "description": "Corner radius / shorter side.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 0.5,
          "default": null
        },
        "polygon": {
          "description": "Pad-local outline, for 'polygon'.",
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "array",
                "prefixItems": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  }
                ],
                "items": false,
                "minItems": 2,
                "maxItems": 2
              }
            },
            {
              "type": "null"
            }
          ],
          "default": null
        }
      },
      "required": [
        "shape",
        "size"
      ],
      "additionalProperties": false
    },
    "Component": {
      "type": "object",
      "description": "A placed part.",
      "properties": {
        "ref": {
          "description": "Reference designator.",
          "type": "string"
        },
        "side": {
          "description": "Mounting side.",
          "type": "string",
          "enum": [
            "top",
            "bottom"
          ]
        },
        "x": {
          "description": "Footprint origin, board frame, mm.",
          "type": "number"
        },
        "y": {
          "description": "Footprint origin, board frame, mm.",
          "type": "number"
        },
        "rotation": {
          "description": "Degrees counter-clockwise seen from the top, as KiCad stores the footprint orientation and its pos file prints it (bottom parts too; see docs/model.md for the placement transform).",
          "type": "number"
        },
        "value": {
          "description": "Value field.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "footprint": {
          "description": "Footprint name: a key in Board.footprints when present, else the source's name.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "mount": {
          "description": "Assembly technology.",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "smd",
            "tht",
            "other",
            null
          ],
          "default": null
        },
        "populate": {
          "description": "False for DNP (do not populate).",
          "type": "boolean",
          "default": true
        },
        "in_bom": {
          "description": "Listed in the BOM.",
          "type": "boolean",
          "default": true
        },
        "in_pos": {
          "description": "Listed in placement (pick-and-place) files.",
          "type": "boolean",
          "default": true
        },
        "mpn": {
          "description": "Manufacturer part numbers (alternates allowed).",
          "type": "array",
          "items": {
            "$ref": "#/$defs/PartNumber"
          },
          "default": []
        },
        "models": {
          "description": "3D models.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/ModelRef"
          },
          "default": []
        },
        "height": {
          "description": "Body height above the board, mm, when known.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "attributes": {
          "description": "Other source fields (KiCad properties, BOM columns).",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "default": {}
        }
      },
      "required": [
        "ref",
        "side",
        "x",
        "y",
        "rotation"
      ],
      "additionalProperties": false
    },
    "Drill": {
      "type": "object",
      "description": "A hole in the board frame: round when x2/y2 are null, otherwise a slot from (x, y) to (x2, y2).",
      "properties": {
        "x": {
          "description": "Centre (slot: first end), mm.",
          "type": "number"
        },
        "y": {
          "description": "Centre (slot: first end), mm.",
          "type": "number"
        },
        "diameter": {
          "description": "Finished hole diameter (slot: width), mm; 0 when the source writes a placeholder.",
          "type": "number",
          "minimum": 0
        },
        "plated": {
          "description": "Plated through hole.",
          "type": "boolean"
        },
        "x2": {
          "description": "Slot: second end.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "y2": {
          "description": "Slot: second end.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "tool": {
          "description": "Excellon tool, e.g. 'T3'.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "function": {
          "description": "Gerber X2 drill function.",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "via",
            "component",
            "mechanical",
            null
          ],
          "default": null
        },
        "filled": {
          "description": "Filled/capped via (not punched in 3D).",
          "type": "boolean",
          "default": false
        },
        "layer": {
          "description": "The drill Layer.id this hole comes from.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "x",
        "y",
        "diameter",
        "plated"
      ],
      "additionalProperties": false
    },
    "Footprint": {
      "type": "object",
      "description": "A footprint definition, shared by components that use it (library orientation, top side).",
      "properties": {
        "name": {
          "description": "Library id, e.g. 'Resistor_SMD:R_0603_1608Metric' (the key in Board.footprints).",
          "type": "string"
        },
        "pads": {
          "description": "Pads.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/Pad"
          },
          "default": []
        },
        "graphics": {
          "description": "Silk/fab/courtyard drawings.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/Graphic"
          },
          "default": []
        },
        "attr": {
          "description": "KiCad footprint attributes as written in the library ('smd', 'through_hole', ...).",
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "Graphic": {
      "type": "object",
      "description": "A footprint drawing (silk, fab, courtyard): arcs/circles flattened, footprint frame.",
      "properties": {
        "layer": {
          "description": "KiCad layer name ('F.SilkS', 'F.Fab', 'F.CrtYd'...).",
          "type": "string"
        },
        "kind": {
          "description": "Original primitive.",
          "type": "string",
          "enum": [
            "line",
            "rect",
            "circle",
            "arc",
            "poly",
            "curve"
          ]
        },
        "pts": {
          "description": "Points.",
          "type": "array",
          "items": {
            "type": "array",
            "prefixItems": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "items": false,
            "minItems": 2,
            "maxItems": 2
          },
          "minItems": 2
        },
        "width": {
          "description": "Stroke width, mm (0 for filled-only).",
          "type": "number",
          "minimum": 0
        },
        "closed": {
          "description": "Closed loop.",
          "type": "boolean",
          "default": false
        },
        "filled": {
          "description": "Filled.",
          "type": "boolean",
          "default": false
        }
      },
      "required": [
        "layer",
        "kind",
        "pts",
        "width"
      ],
      "additionalProperties": false
    },
    "ImpedanceLayer": {
      "type": "object",
      "description": "Geometry a target applies to on one signal layer (KiCad tuning profile layer entry, IPC-2581 Impedance).",
      "properties": {
        "layer": {
          "description": "Signal layer ('F.Cu', 'In1.Cu').",
          "type": "string"
        },
        "width": {
          "description": "Track width, mm.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "gap": {
          "description": "Differential pair gap, mm.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "ref_top": {
          "description": "Reference plane above, if any.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "ref_bottom": {
          "description": "Reference plane below, if any.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "layer"
      ],
      "additionalProperties": false
    },
    "ImpedanceTarget": {
      "type": "object",
      "description": "A controlled-impedance target.",
      "properties": {
        "kind": {
          "description": "Single-ended Z0 or differential Zdiff.",
          "type": "string",
          "enum": [
            "single",
            "differential"
          ]
        },
        "target": {
          "description": "Ohms.",
          "type": "number",
          "exclusiveMinimum": 0
        },
        "tolerance_pct": {
          "description": "Allowed deviation, percent (10 = +-10 %); null = unspecified.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "common_mode": {
          "description": "Differential: common-mode target, ohms, when given (class names like BAL_D90_C30).",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "structure": {
          "description": "Transmission-line structure, when the source says (MS, SL, CPW, CPWG).",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "microstrip",
            "stripline",
            "coplanar",
            "coplanar_grounded",
            null
          ],
          "default": null
        },
        "source": {
          "description": "Where the target comes from: a KiCad tuning profile, an IPC-2581/ODB++ spec, the class name convention (SE_50_CP, DP_90_MS, 90ohm...) or a user entry.",
          "type": "string",
          "enum": [
            "tuning_profile",
            "ipc2581",
            "odbpp",
            "name",
            "user"
          ]
        },
        "layers": {
          "description": "Per-layer geometry, when the source gives it.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/ImpedanceLayer"
          },
          "default": []
        }
      },
      "required": [
        "kind",
        "target",
        "source"
      ],
      "additionalProperties": false
    },
    "Layer": {
      "type": "object",
      "description": "One drawable layer (a Gerber, an ODB++ layer, a drill file...).",
      "properties": {
        "id": {
          "description": "Unique id; KiCad canonical names where they apply ('F.Cu', 'In1.Cu', 'Edge.Cuts', 'PTH').",
          "type": "string"
        },
        "role": {
          "description": "What the layer is.",
          "type": "string",
          "enum": [
            "copper",
            "mask",
            "paste",
            "silk",
            "outline",
            "drill",
            "fab",
            "courtyard",
            "adhesive",
            "user",
            "other"
          ]
        },
        "side": {
          "description": "Board side; 'none' for outline/drill/user layers.",
          "type": "string",
          "enum": [
            "top",
            "bottom",
            "inner",
            "none"
          ]
        },
        "order": {
          "description": "Stack position: copper 1..N top to bottom (Gerber L<n>); other layers ascend in drawing order.",
          "type": "integer",
          "minimum": 0
        },
        "files": {
          "description": "SourceFile paths that draw this layer (usually one).",
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        },
        "format": {
          "description": "Format of the files.",
          "type": "string",
          "enum": [
            "gerber",
            "excellon",
            "odb",
            "ipc2581",
            "svg",
            "other"
          ],
          "default": "gerber"
        },
        "polarity": {
          "description": "Gerber X2 file polarity.",
          "type": "string",
          "enum": [
            "positive",
            "negative"
          ],
          "default": "positive"
        },
        "function": {
          "description": "Raw Gerber X2 %TF.FileFunction (or ODB++ layer type).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "plated": {
          "description": "Drill layers: plated (PTH) or not (NPTH); null when mixed.",
          "type": [
            "boolean",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "id",
        "role",
        "side",
        "order"
      ],
      "additionalProperties": false
    },
    "ModelRef": {
      "type": "object",
      "description": "A 3D model placed on a component (KiCad (model ...) semantics).",
      "properties": {
        "path": {
          "description": "Model path as the source writes it (env vars like ${KICAD9_3DMODEL_DIR} kept).",
          "type": "string"
        },
        "offset": {
          "description": "mm, footprint frame (KiCad 3D viewer: x right, y up, z up).",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 3,
          "maxItems": 3,
          "default": [
            0.0,
            0.0,
            0.0
          ]
        },
        "rotate": {
          "description": "Degrees about x, y, z.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 3,
          "maxItems": 3,
          "default": [
            0.0,
            0.0,
            0.0
          ]
        },
        "scale": {
          "description": "Scale.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 3,
          "maxItems": 3,
          "default": [
            1.0,
            1.0,
            1.0
          ]
        },
        "hide": {
          "description": "Hidden in the 3D view.",
          "type": "boolean",
          "default": false
        }
      },
      "required": [
        "path"
      ],
      "additionalProperties": false
    },
    "Net": {
      "type": "object",
      "description": "An electrical net.",
      "properties": {
        "name": {
          "description": "Net name as the source writes it ('/USB/D+', 'GND').",
          "type": "string"
        },
        "net_class": {
          "description": "The NetClass.name it belongs to ('Default' when the source assigns none).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "pair": {
          "description": "The partner net of a differential pair (KiCad pairs '+'/'-' and 'P'/'N' suffixes).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "NetClass": {
      "type": "object",
      "description": "A net class (KiCad .kicad_pro net_settings) with its design rules and impedance target.",
      "properties": {
        "name": {
          "description": "Class name.",
          "type": "string"
        },
        "nets": {
          "description": "Net names in the class.",
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        },
        "patterns": {
          "description": "Assignment patterns (KiCad netclass_patterns, wildcards).",
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        },
        "track_width": {
          "description": "mm.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "clearance": {
          "description": "mm.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "diff_pair_width": {
          "description": "mm.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "diff_pair_gap": {
          "description": "mm.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "via_diameter": {
          "description": "mm.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "via_drill": {
          "description": "mm.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "priority": {
          "description": "KiCad priority (lower wins; Default is the largest).",
          "type": [
            "integer",
            "null"
          ],
          "default": null
        },
        "tuning_profile": {
          "description": "KiCad 10 tuning profile name, when set.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "impedance": {
          "description": "Controlled-impedance target, when known.",
          "anyOf": [
            {
              "$ref": "#/$defs/ImpedanceTarget"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "Origin": {
      "type": "object",
      "description": "Origins the source defines besides the file origin, in the board frame, so writers can go back.",
      "properties": {
        "aux": {
          "description": "Auxiliary (place/drill-file) origin, e.g. KiCad's aux_axis_origin.",
          "anyOf": [
            {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "grid": {
          "description": "Grid origin.",
          "anyOf": [
            {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "drill": {
          "description": "Origin the drill files were written relative to, when not the file origin.",
          "anyOf": [
            {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            {
              "type": "null"
            }
          ],
          "default": null
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "Outline": {
      "type": "object",
      "description": "The board shape: arcs flattened to polylines, loops implicitly closed (last point != first).",
      "properties": {
        "board": {
          "description": "The outer edge, counter-clockwise.",
          "type": "array",
          "items": {
            "type": "array",
            "prefixItems": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "items": false,
            "minItems": 2,
            "maxItems": 2
          },
          "minItems": 3
        },
        "cutouts": {
          "description": "Internal cutouts (routed holes, slots wider than a drill), clockwise.",
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            "minItems": 3
          },
          "default": []
        },
        "approximate": {
          "description": "True when the edge is a fallback (bounding box, convex hull) rather than the real profile.",
          "type": "boolean",
          "default": false
        }
      },
      "required": [
        "board"
      ],
      "additionalProperties": false
    },
    "Pad": {
      "type": "object",
      "description": "boarddd's JS Pad (src/geom/pads.js, checked against pcbnew) plus magpie's extra fields.",
      "properties": {
        "number": {
          "description": "Pad number/name ('' for unnumbered pads).",
          "type": "string"
        },
        "type": {
          "description": "KiCad pad type.",
          "type": "string",
          "enum": [
            "smd",
            "thru_hole",
            "np_thru_hole",
            "connect"
          ]
        },
        "shape": {
          "description": "KiCad pad shape.",
          "type": "string",
          "enum": [
            "circle",
            "rect",
            "oval",
            "roundrect",
            "chamfered_rect",
            "trapezoid",
            "custom"
          ]
        },
        "at": {
          "description": "x, y (footprint frame, y down) and rotation in degrees relative to the footprint.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 3,
          "maxItems": 3
        },
        "size": {
          "description": "Width, height, mm.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "layers": {
          "description": "KiCad layer names, wildcards kept ('*.Cu', 'F.Paste'...).",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "drill": {
          "description": "The hole, for thru_hole/np_thru_hole.",
          "anyOf": [
            {
              "$ref": "#/$defs/PadDrill"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "offset": {
          "description": "Copper shape offset of a pad without a hole (castellated SMD pads); pads with one keep it in drill.offset.",
          "anyOf": [
            {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "roundrect_rratio": {
          "description": "roundrect/chamfered: corner radius / shorter side.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 0.5,
          "default": null
        },
        "chamfer_ratio": {
          "description": "chamfered_rect: chamfer / shorter side.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 0.5,
          "default": null
        },
        "chamfer": {
          "description": "chamfered_rect: which corners.",
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "top_left",
                  "top_right",
                  "bottom_left",
                  "bottom_right"
                ]
              }
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "rect_delta": {
          "description": "trapezoid: KiCad rect_delta.",
          "anyOf": [
            {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "anchor": {
          "description": "custom: anchor shape.",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "circle",
            "rect",
            null
          ],
          "default": null
        },
        "primitives": {
          "description": "custom: primitives as filled loops, pad-local.",
          "anyOf": [
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/Primitive"
              }
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "solder_mask_margin": {
          "description": "Pad mask expansion override, mm.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "solder_paste_margin": {
          "description": "Pad paste expansion override, mm.",
          "type": [
            "number",
            "null"
          ],
          "default": null
        },
        "function": {
          "description": "Pad function/net role when the source says ('ground', 'heatsink', 'fiducial'...).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "paste": {
          "description": "Paste openings when they differ from the copper; null = unknown/as copper, [] = no paste.",
          "anyOf": [
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/Aperture"
              }
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "mask": {
          "description": "Mask opening when it differs from copper + margin.",
          "anyOf": [
            {
              "$ref": "#/$defs/Aperture"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "holes": {
          "description": "Extra holes (rare; multi-drill pads from ODB++/IPC-2581).",
          "anyOf": [
            {
              "type": "array",
              "items": {
                "$ref": "#/$defs/PadDrill"
              }
            },
            {
              "type": "null"
            }
          ],
          "default": null
        }
      },
      "required": [
        "number",
        "type",
        "shape",
        "at",
        "size",
        "layers"
      ],
      "additionalProperties": false
    },
    "PadDrill": {
      "type": "object",
      "description": "A pad's hole; an oval hole runs along its long axis.",
      "properties": {
        "shape": {
          "description": "Hole shape.",
          "type": "string",
          "enum": [
            "circle",
            "oval"
          ]
        },
        "size": {
          "description": "Width, height (circle: both the diameter), mm.",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2
        },
        "offset": {
          "description": "Copper offset relative to the hole (KiCad (drill (offset)) semantics).",
          "type": "array",
          "prefixItems": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "items": false,
          "minItems": 2,
          "maxItems": 2,
          "default": [
            0.0,
            0.0
          ]
        }
      },
      "required": [
        "shape",
        "size"
      ],
      "additionalProperties": false
    },
    "Panel": {
      "type": "object",
      "description": "Panelisation, when the source is a panel of identical boards.",
      "properties": {
        "instances": {
          "description": "Board copies.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/PanelInstance"
          },
          "default": []
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "PanelInstance": {
      "type": "object",
      "description": "One board copy in a panel, board frame of the panel.",
      "properties": {
        "x": {
          "description": "Offset, mm.",
          "type": "number"
        },
        "y": {
          "description": "Offset, mm.",
          "type": "number"
        },
        "rotation": {
          "description": "Degrees counter-clockwise.",
          "type": "number",
          "default": 0.0
        }
      },
      "required": [
        "x",
        "y"
      ],
      "additionalProperties": false
    },
    "PartNumber": {
      "type": "object",
      "description": "A manufacturer part number.",
      "properties": {
        "mpn": {
          "description": "Manufacturer part number.",
          "type": "string"
        },
        "manufacturer": {
          "description": "Manufacturer.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "mpn"
      ],
      "additionalProperties": false
    },
    "Primitive": {
      "type": "object",
      "description": "A custom-pad primitive flattened to a filled loop, pad-local.",
      "properties": {
        "pts": {
          "description": "Loop points.",
          "type": "array",
          "items": {
            "type": "array",
            "prefixItems": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "items": false,
            "minItems": 2,
            "maxItems": 2
          },
          "minItems": 3
        }
      },
      "required": [
        "pts"
      ],
      "additionalProperties": false
    },
    "SideValues": {
      "type": "object",
      "description": "A value per board side.",
      "properties": {
        "top": {
          "description": "Top side.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "bottom": {
          "description": "Bottom side.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "Source": {
      "type": "object",
      "description": "Where the model came from (provenance).",
      "properties": {
        "kind": {
          "description": "The primary input format the reader used.",
          "type": "string",
          "enum": [
            "kicad_pcb",
            "gerber",
            "odbpp",
            "ipc2581",
            "step",
            "other"
          ]
        },
        "files": {
          "description": "Input files.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/SourceFile"
          },
          "default": []
        },
        "generator": {
          "description": "The tool that wrote the inputs, e.g. 'KiCad Pcbnew 10.0.6' (Gerber X2/gbrjob GenerationSoftware).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "reader": {
          "description": "The reader that built this model, e.g. 'boarddd 0.2.0 io.kicad'.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "created": {
          "description": "When the inputs were made (ISO 8601), if the source says.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "commit": {
          "description": "VCS commit of the design (kipr: the head sha).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "ref": {
          "description": "VCS ref or upload/package id the inputs belong to.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      },
      "required": [
        "kind"
      ],
      "additionalProperties": false
    },
    "SourceFile": {
      "type": "object",
      "description": "One input file the model was read from.",
      "properties": {
        "path": {
          "description": "Path relative to the source root (package, project folder or archive).",
          "type": "string"
        },
        "role": {
          "description": "What the file holds.",
          "type": "string",
          "enum": [
            "pcb",
            "copper",
            "mask",
            "paste",
            "silk",
            "outline",
            "drill",
            "drill_map",
            "fab",
            "job",
            "placement",
            "bom",
            "netlist",
            "model",
            "odb",
            "ipc2581",
            "other"
          ]
        },
        "side": {
          "description": "Board side, for layer files.",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "top",
            "bottom",
            "inner",
            "none",
            null
          ],
          "default": null
        },
        "sha256": {
          "description": "Lower-case hex SHA-256 of the file's bytes.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9a-f]{64}$",
          "default": null
        }
      },
      "required": [
        "path",
        "role"
      ],
      "additionalProperties": false
    },
    "Stackup": {
      "type": "object",
      "description": "Board build: thickness, finish, colours, copper count and the physical layers.",
      "properties": {
        "thickness": {
          "description": "Finished board thickness, mm.",
          "type": [
            "number",
            "null"
          ],
          "exclusiveMinimum": 0,
          "default": null
        },
        "copper_layers": {
          "description": "Number of copper layers.",
          "type": [
            "integer",
            "null"
          ],
          "minimum": 1,
          "default": null
        },
        "finish": {
          "description": "Surface finish as the source names it ('ENIG', 'HASL', 'OSP', 'None'...).",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "mask_color": {
          "description": "Solder mask colour per side.",
          "$ref": "#/$defs/SideValues",
          "default": {
            "top": null,
            "bottom": null
          }
        },
        "silk_color": {
          "description": "Silkscreen colour per side.",
          "$ref": "#/$defs/SideValues",
          "default": {
            "top": null,
            "bottom": null
          }
        },
        "layers": {
          "description": "Physical layers top to bottom; empty when the source has no stackup.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/StackupLayer"
          },
          "default": []
        },
        "impedance_controlled": {
          "description": "The board is ordered impedance controlled (KiCad dielectric_constraints, gbrjob ImpedanceControlled).",
          "type": [
            "boolean",
            "null"
          ],
          "default": null
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "StackupLayer": {
      "type": "object",
      "description": "One physical layer, listed top to bottom.",
      "properties": {
        "name": {
          "description": "Source name: 'F.Cu', 'dielectric 1', 'Top Solder Mask'...",
          "type": "string"
        },
        "kind": {
          "description": "Material role.",
          "type": "string",
          "enum": [
            "silk",
            "paste",
            "mask",
            "copper",
            "dielectric",
            "other"
          ]
        },
        "side": {
          "description": "'inner' for inner copper and dielectrics.",
          "type": "string",
          "enum": [
            "top",
            "bottom",
            "inner",
            "none"
          ]
        },
        "thickness": {
          "description": "mm (with sublayers: their sum).",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "material": {
          "description": "'FR4', 'Polyimide'... (with sublayers of different materials: their names joined by ' + ').",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "color": {
          "description": "Colour as the source names it: a name ('Blue', 'Matte Black') or '#RRGGBB'.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "epsilon_r": {
          "description": "Dielectric constant (with sublayers: the series value, total thickness / sum(thickness_i / epsilon_r_i)).",
          "type": [
            "number",
            "null"
          ],
          "exclusiveMinimum": 0,
          "default": null
        },
        "loss_tangent": {
          "description": "Dielectric loss tangent (with sublayers: the thickness-weighted mean).",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "layer": {
          "description": "The Layer.id this physical layer is drawn by, if any.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "dielectric": {
          "description": "Dielectrics: prepreg or core, when the source says (KiCad type, IPC-2581 DIELPREG/DIELCORE).",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "prepreg",
            "core",
            null
          ],
          "default": null
        },
        "sublayers": {
          "description": "Dielectrics the source splits into parts, top to bottom, the first included; empty otherwise.",
          "type": "array",
          "items": {
            "$ref": "#/$defs/StackupSublayer"
          },
          "default": []
        },
        "frequency": {
          "description": "Hz at which epsilon_r and loss_tangent are given (KiCad spec_frequency, ODB++ FrequencyVal).",
          "type": [
            "number",
            "null"
          ],
          "exclusiveMinimum": 0,
          "default": null
        },
        "dielectric_model": {
          "description": "How epsilon_r/loss_tangent vary with frequency (KiCad dielectric_model).",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "constant",
            "djordjevic_sarkar",
            null
          ],
          "default": null
        },
        "locked": {
          "description": "Thickness fixed for impedance control (KiCad '(thickness ... locked)').",
          "type": [
            "boolean",
            "null"
          ],
          "default": null
        },
        "tolerance": {
          "description": "Manufacturing tolerances, when the source gives them.",
          "anyOf": [
            {
              "$ref": "#/$defs/Tolerance"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "finished_thickness": {
          "description": "Copper: plated (finished) thickness, mm, when it differs from the base foil.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "roughness_rq": {
          "description": "Copper: RMS surface roughness, mm (0.0005 = 0.5 um).",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "conductivity": {
          "description": "Copper: conductivity, S/m.",
          "type": [
            "number",
            "null"
          ],
          "exclusiveMinimum": 0,
          "default": null
        },
        "etch_factor": {
          "description": "Copper: etch factor (thickness / one side's undercut), for trapezoidal traces.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "thickness_over_copper": {
          "description": "Solder mask: thickness over the traces, mm, when it differs from 'thickness' (over the laminate).",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        }
      },
      "required": [
        "name",
        "kind",
        "side"
      ],
      "additionalProperties": false
    },
    "StackupSublayer": {
      "type": "object",
      "description": "One part of a dielectric the source splits into several (KiCad ``addsublayer``, gbrjob '(1/2)' entries).",
      "properties": {
        "thickness": {
          "description": "mm.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        },
        "material": {
          "description": "Material name, e.g. '2116 RC58%'.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "color": {
          "description": "Colour as the source names it.",
          "type": [
            "string",
            "null"
          ],
          "default": null
        },
        "epsilon_r": {
          "description": "Dielectric constant.",
          "type": [
            "number",
            "null"
          ],
          "exclusiveMinimum": 0,
          "default": null
        },
        "loss_tangent": {
          "description": "Dielectric loss tangent.",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "default": null
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "Tolerance": {
      "type": "object",
      "description": "Manufacturing tolerances of a stackup layer, as [minus, plus] deviations (IPC-2581 tolPlus/tolMinus).",
      "properties": {
        "thickness": {
          "description": "[minus, plus] in mm, e.g. [-0.01, 0.01].",
          "anyOf": [
            {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "epsilon_r": {
          "description": "[minus, plus] of the dielectric constant.",
          "anyOf": [
            {
              "type": "array",
              "prefixItems": [
                {
                  "type": "number"
                },
                {
                  "type": "number"
                }
              ],
              "items": false,
              "minItems": 2,
              "maxItems": 2
            },
            {
              "type": "null"
            }
          ],
          "default": null
        }
      },
      "required": [],
      "additionalProperties": false
    }
  }
};
