// Writes fixtures/impedance/field-sweep.json: boarddd's own field solver (src/impedance/fieldsolver.js, MIT) on
// the geometries of the tier-1 accuracy sweep, on a fine grid (levels 2 and 3, extrapolated). It replaced
// qs-sweep.json (the same geometries solved by a GPL tool) as the reference the tier-1 "boarddd" corrections are
// fitted to and checked against. Takes about ten minutes; the tests recompute a sample of rows.
// Usage: node fixtures/impedance/make_field_sweep.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fieldCalculate } from '../../src/impedance/fieldsolver.js';

export const SWEEP_OPTS = { level: 2, maxLevel: 3, tol: 1 };
/** The sweep's via fence for cpwg: as in qs-sweep.json, max(0.5, 2h) mm from the gap. */
export const fenceFor = (args) => Math.max(0.5, 2 * args.h);

export function sweepRow(model, args, keys) {
  const p = model === 'cpwg' ? { ...args, fence: fenceFor(args) } : args;
  const r = fieldCalculate(model, p, SWEEP_OPTS);
  const ref = Object.fromEntries(keys.map((k) => [k, Number(r[k].toFixed(4))]));
  return [model, args, ref, Number(r.error_pct.toFixed(3))];
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const qs = JSON.parse(readFileSync(new URL('./qs-sweep.json', import.meta.url), 'utf8'));
  const rows = [];
  const t0 = Date.now();
  for (const [model, args, ref] of qs.rows) {
    rows.push(sweepRow(model, args, Object.keys(ref)));
    if (rows.length % 100 === 0) console.error(rows.length, `${((Date.now() - t0) / 1000).toFixed(0)} s`);
  }
  const out = {
    about: 'Quasi-static 2D field solutions from boarddd\'s own solver (src/impedance/fieldsolver.js, MIT), grid levels 2 and 3 extrapolated; generated by make_field_sweep.mjs. Lengths mm; the geometries of qs-sweep.json: t = 0.0001 stands in for a zero-thickness strip; coplanar grounds are infinite with a via fence (a ground wall through the substrate) at max(0.5, 2h) from the gap; the mask in coated_microstrip is conformal (c over laminate, trace top and sides). est_pct: the solver\'s error estimate for the finer grid (the extrapolated value is typically ten times closer).',
    columns: ['model', 'args', 'ref', 'est_pct'],
    rows,
  };
  writeFileSync(new URL('./field-sweep.json', import.meta.url), `{\n "about": ${JSON.stringify(out.about)},\n "columns": ${JSON.stringify(out.columns)},\n "rows": [\n${rows.map((r) => `  ${JSON.stringify(r)}`).join(',\n')}\n ]\n}\n`);
  console.error('done', `${((Date.now() - t0) / 1000).toFixed(0)} s`);
}
