"""scikit-rf reference values for boarddd's loss model (fixtures/impedance/skrf-loss-refs.json).

scikit-rf (BSD-3) is used only as an independent check: its media.MLine implements the same papers (Djordjevic-Sarkar
as "djordjevicsvensson", Kirschning-Jansen dispersion, Hammerstad-Jensen) in its own code. Nothing of it is copied
into boarddd; only these numbers are stored, and fixtures/impedance/make_loss_cases.mjs turns them into goldens.
Usage: python fixtures/impedance/skrf_loss_refs.py   (needs scikit-rf: pip install "boarddd[dev]")
"""

from __future__ import annotations

import json
import sys
import warnings
from pathlib import Path

import numpy as np
import skrf as rf
from skrf.media import MLine

OUT = Path(__file__).with_name("skrf-loss-refs.json")
FREQS = [1e8, 1e9, 5e9, 1e10, 2e10, 4e10]
# w, h, t (mm), er and tand at f_ref, f_ref (Hz)
LINES = [
    {"w": 0.36, "h": 0.2104, "t": 0.035, "er": 4.4, "tand": 0.02, "f_ref": 1e9},
    {"w": 0.15, "h": 0.1, "t": 0.018, "er": 3.66, "tand": 0.0037, "f_ref": 1e10},
    {"w": 1.5, "h": 0.794, "t": 0.035, "er": 4.2, "tand": 0.02, "f_ref": 1e9},
    {"w": 3.0, "h": 1.6, "t": 0.035, "er": 4.5, "tand": 0.015, "f_ref": 1e9},
]


def rows() -> list[dict]:
    out = []
    for p in LINES:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            ml = MLine(
                frequency=rf.Frequency.from_f(np.array(FREQS), unit="hz"),
                w=p["w"] * 1e-3,
                h=p["h"] * 1e-3,
                t=p["t"] * 1e-3,
                ep_r=p["er"],
                tand=p["tand"],
                rho=1 / 5.8e7,
                rough=0,
                disp="kirschningjansen",
                diel="djordjevicsvensson",
                f_epr_tand=p["f_ref"],
                f_low=1e3,
                f_high=1e12,
                model="hammerstadjensen",
                compatibility_mode="qucs",
            )
        out.append(
            {
                "line": p,
                "frequency": FREQS,
                "er_f": [float(np.real(v)) for v in ml.ep_r_f],
                "tand_f": [float(v) for v in ml.tand_f],
                "Z0_static": [float(np.real(v)) for v in ml.zl_eff],
                "eps_eff_static": [float(np.real(v)) for v in ml.ep_reff],
                "Z0_f": [float(np.real(v)) for v in ml._z_characteristic],
                "eps_eff_f": [float(np.real(v)) for v in ml.ep_reff_f],
                "alpha_d": [float(v) for v in ml.alpha_dielectric],
                "alpha_c_hammerstad": [float(v) for v in ml.alpha_conductor],
            }
        )
    return out


def main() -> int:
    data = {
        "about": "scikit-rf media.MLine (compatibility_mode='qucs', djordjevicsvensson, kirschningjansen, "
        "hammerstadjensen, smooth copper 5.8e7 S/m) as an independent check; generated by skrf_loss_refs.py.",
        "skrf": rf.__version__,
        "rows": rows(),
    }
    OUT.write_text(json.dumps(data, indent=1) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
