"""Generate schema/board.schema.json, src/model/schema.js and src/model/board.d.ts from boarddd.model.

The schema uses a small JSON Schema 2020-12 subset that both hand-written validators (Python
boarddd.validate, JS src/model/index.js) implement: type, const, enum, properties, required,
additionalProperties, items, prefixItems, minItems, maxItems, minimum, maximum, exclusiveMinimum,
pattern, anyOf, $ref (#/$defs/...).
"""

from __future__ import annotations

import json
import types
from dataclasses import MISSING, fields, is_dataclass
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin

from . import model

HEADER = "Generated by `python -m boarddd.model --write` from python/src/boarddd/model.py. Do not edit."


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _is_optional(tp: Any) -> tuple[bool, Any]:
    origin, args = get_origin(tp), get_args(tp)
    if (origin is Union or origin is types.UnionType) and type(None) in args:
        rest = [a for a in args if a is not type(None)]
        return True, rest[0] if len(rest) == 1 else Union[tuple(rest)]  # noqa: UP007
    return False, tp


def _desc(cls: type) -> str:
    return " ".join((cls.__doc__ or "").split())


class _Gen:
    def __init__(self) -> None:
        self.defs: dict[str, Any] = {}

    def type_schema(self, tp: Any) -> dict[str, Any]:
        optional, tp = _is_optional(tp)
        s = self._schema(tp)
        if not optional:
            return s
        if set(s) <= {"type", "enum"} and isinstance(s.get("type"), str):
            s = dict(s, type=[s["type"], "null"])
            if "enum" in s:
                s["enum"] = [*s["enum"], None]
            return s
        return {"anyOf": [s, {"type": "null"}]}

    def _schema(self, tp: Any) -> dict[str, Any]:
        origin, args = get_origin(tp), get_args(tp)
        if tp is str:
            return {"type": "string"}
        if tp is bool:
            return {"type": "boolean"}
        if tp is int:
            return {"type": "integer"}
        if tp is float:
            return {"type": "number"}
        if tp is Any:
            return {}
        if origin is Literal:
            if len(args) == 1:
                return {"const": args[0]}
            return {"type": "string", "enum": list(args)}
        if origin is list:
            return {"type": "array", "items": self.type_schema(args[0])}
        if origin is tuple:
            return {
                "type": "array",
                "prefixItems": [self.type_schema(a) for a in args],
                "items": False,
                "minItems": len(args),
                "maxItems": len(args),
            }
        if origin is dict:
            return {"type": "object", "additionalProperties": self.type_schema(args[1])}
        if is_dataclass(tp):
            self.define(tp)
            return {"$ref": f"#/$defs/{tp.__name__}"}
        raise TypeError(f"unsupported type {tp!r}")

    def define(self, cls: type) -> dict[str, Any]:
        if cls.__name__ in self.defs:
            return self.defs[cls.__name__]
        obj: dict[str, Any] = {"type": "object", "description": _desc(cls)}
        self.defs[cls.__name__] = obj  # before recursing (no cycles today, but cheap)
        hints = model._hints(cls)
        props: dict[str, Any] = {}
        required = []
        for f in fields(cls):
            s = self.type_schema(hints[f.name])
            extra = dict(f.metadata.get("schema", {}))
            must = extra.pop("required", False)  # has a Python default but documents must state it
            item_extra = extra.pop("items", None)
            if item_extra:
                s = dict(s, items=dict(s["items"], **item_extra))
            if extra:
                target = s["anyOf"][0] if "anyOf" in s else s
                target.update(extra)
            if f.metadata.get("doc"):
                s = {"description": f.metadata["doc"], **s}
            if must:
                required.append(f.name)
            elif f.default is not MISSING:
                s["default"] = model.to_dict(f.default)
            elif f.default_factory is not MISSING:
                s["default"] = model.to_dict(f.default_factory())
            else:
                required.append(f.name)
            props[f.name] = s
        obj["properties"] = props
        obj["required"] = required
        obj["additionalProperties"] = False
        return obj


def schema() -> dict[str, Any]:
    g = _Gen()
    root = g.define(model.Board)
    defs = {k: v for k, v in g.defs.items() if k != "Board"}
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": model.SCHEMA_ID,
        "$comment": HEADER,
        "title": "boarddd board model",
        **root,
        "$defs": dict(sorted(defs.items())),
    }


# ---------------------------------------------------------------------------------------------------------------------
# TypeScript


def _ts(tp: Any) -> str:
    optional, tp = _is_optional(tp)
    t = _ts_inner(tp)
    return f"{t} | null" if optional else t


def _ts_inner(tp: Any) -> str:
    origin, args = get_origin(tp), get_args(tp)
    if tp is str:
        return "string"
    if tp is bool:
        return "boolean"
    if tp in (int, float):
        return "number"
    if tp is Any:
        return "unknown"
    if origin is Literal:
        return " | ".join(json.dumps(a) for a in args)
    if origin is list:
        inner = _ts(args[0])
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if origin is tuple:
        if all(a is float for a in args) and len(args) in (2, 3):
            return f"Vec{len(args)}"
        return "[" + ", ".join(_ts(a) for a in args) + "]"
    if origin is dict:
        return f"Record<string, {_ts(args[1])}>"
    if is_dataclass(tp):
        return tp.__name__
    raise TypeError(f"unsupported type {tp!r}")


def _classes() -> list[type]:
    seen: list[type] = []

    def walk(tp: Any) -> None:
        for a in get_args(tp):
            walk(a)
        if is_dataclass(tp) and tp not in seen:
            seen.append(tp)
            for f in fields(tp):
                walk(model._hints(tp)[f.name])

    walk(model.Board)
    return seen


def dts() -> str:
    out = [f"// {HEADER}", "// The boarddd/board@1 model; see docs/model.md.", ""]
    out.append(f"export type SchemaId = {json.dumps(model.SCHEMA_ID)};")
    out.append("/** x, y in mm. */")
    out.append("export type Vec2 = [number, number];")
    out.append("export type Vec3 = [number, number, number];")
    out.append("")
    for cls in _classes():
        out.append(f"/** {_desc(cls)} */")
        out.append(f"export interface {cls.__name__} {{")
        hints = model._hints(cls)
        for f in fields(cls):
            must = f.metadata.get("schema", {}).get("required", False)
            opt = "?" if not must and (f.default is not MISSING or f.default_factory is not MISSING) else ""
            text = f.metadata.get("doc")
            if text:
                out.append(f"  /** {text} */")
            out.append(f"  {f.name}{opt}: {_ts(hints[f.name])};")
        out.append("}")
        out.append("")
    return "\n".join(out)


def schema_js(text: str) -> str:
    return f"// {HEADER}\n// The same object as schema/board.schema.json, as an ES module (no JSON imports needed).\nexport default {text.rstrip()};\n"


def outputs() -> dict[str, str]:
    text = json.dumps(schema(), indent=2, ensure_ascii=False) + "\n"
    return {
        "schema/board.schema.json": text,
        "src/model/schema.js": schema_js(text),
        "src/model/board.d.ts": dts(),
    }
